### PR TITLE
Added my e-sig (Micah)

### PR DESCRIPTION
**Pull request by asuh**
Added my name to the signees file

### CODE REVIEW

**Review by andrewcarolan — APPROVED** [review]
⛩️

**Comment by alexdilley** [comment]
Sorry, @asuh! First merge conflict for you to deal with!

**Comment by asuh** [comment]
@andrewcarolan and @alexdilley Fixed!

**Comment by alexdilley** [comment]
Hey @asuh. A good rule of thumb is to only merge backwards, not forwards (i.e. `master` shouldn't be merged into feature branches, but feature branches [eventually] into `master`, etc). To align your branch with newer changes on `master`, it's normally best to `rebase` with `master` instead; the result should be a cleaner history. We should probably check policy with the team, though, but I'm happy to walk you through it if that doesn't make sense...I'm clocking-off shortly, however.

**Review by andrewcarolan — APPROVED** [review]

**Comment by andrewcarolan** [comment]
> A good rule of thumb is to only merge backwards, not forwards (i.e. master shouldn't be merged into feature branches, but feature branches [eventually] into master, etc). To align your branch with newer changes on master, it's normally best to rebase with master instead; the result should be a cleaner history. We should probably check policy with the team, though, but I'm happy to walk you through it if that doesn't make sense...I'm clocking-off shortly, however.

By convention we'll usually rebase, but I wouldn't say there's anything wrong with bringing the latest from `master` into your feature branch using a merge.

**Comment by alexdilley** [comment]
As you say, here we are discussing the merits of conflict resolution strategies against the `code-of-conduct` repo 😅 

@asuh apologies for pushing (no pun!) a certain approach; as @andrewcarolan indicates, the intended outcome is the same – that's what's important here. I'm somewhat of a 🦕 that still visualises git graphs!

**Comment by asuh** [comment]
I can always improve my git knowledge and abilities so it's appreciated feedback! I often take a simple route of getting things done but I like rebasing when possible to keep things clean. It's awesome to have a visual look at git, something pretty useful!

**Comment by jkburges** [comment]
I think this is good to be merged @asuh?

**Comment by asuh** [comment]
Oh, forgot all about this! Yes, it's good to go.

**Pull request merged**
