### PR TITLE
Add Alex Dilley

### PR DESCRIPTION
**Pull request by alexdilley**
Very on board with this!

### CODE REVIEW

**Comment by alexdilley** [comment]
Apologies for the force-push on my first contribution to Biteable! 🙈 Omitted to configure `user.email` git setting appropriately.

**Comment by andrewcarolan** [comment]
> Apologies for the force-push

We almost exclusively rebase rather than merge, so you'll see plenty of force pushes round these parts. 🤓

**Review by andrewcarolan — APPROVED** [review]
🐚

**Comment by alexdilley** [comment]
Thanks @andrewcarolan. On that note, do you tend to prefer a "rebase and merge" (where possible) to retain a clean history or an explicit merge commit to indicate the branching (as appears to be the case, at least with this repo)?

**Comment by andrewcarolan** [comment]
> Thanks @andrewcarolan. On that note, do you tend to prefer a "rebase and merge" (where possible) to retain a clean history, or an explicit merge commit to indicate the branching (as appears to be the case, at least with this repo)?

"Create a merge commit" is good when merging a PR.

**Pull request merged**
